print("Hello folks welcome to my site")
name= input('what is your name? ')
birthY=input('enter your birth year ')
type= input('what is your type ')
age=2022-int(birthY)
print(name+' likes '+type+' people and he is '+birthY+' borned and is '+str(age)+ ' years old ')
print("a complete ass hole he is")
a=input('enter a no.')
b=input('enter another no')
c=input('enter anotherrrrr')
d=input('inter newwww no.')
print('now wait for the load')
f=int(a)+int(b)+int(c)+int(d)
print(f)
fot='python is "bad"'
print(fot)
print(fot[7])